export const WILAYA_NAMES: string[] = [
    "Adrar",
    "Chlef",
    "Laghouat",
    "Oum El Bouaghi",
    "Batna",
    "Bejaia",
    "Biskra",
    "Bechar",
    "Blida",
    "Bouira",
    "Tamanrasset",
    "Tebessa",
    "Tlemcen",
    "Tiaret",
    "Tizi Ouzou",
    "Algiers",
    "Djelfa",
    "Jijel",
    "Setif",
    "Saida",
    "Skikda",
    "Sidi Bel Abbes",
    "Annaba",
    "Guelma",
    "Constantine",
    "Medea",
    "Mostaganem",
    "M'Sila",
    "Mascara",
    "Ouargla",
    "Oran",
    "El Bayadh",
    "Illizi",
    "Bordj Bou Arreridj",
    "Boumerdes",
    "El Tarf",
    "Tindouf",
    "Tissemsilt",
    "El Oued",
    "Khenchela",
    "Souk Ahras",
    "Tipaza",
    "Mila",
    "Ain Defla",
    "Naama",
    "Ain Temouchent",
    "Ghardaia",
    "Relizane",
    "El M'Ghair",
    "El Meniaa",
    "Ouled Djellal",
    "Beni Abbes",
    "Timimoun",
    "Bordj Badji Mokhtar",
    "Touggourt",
    "Djanet",
    "In Salah",
    "In Guezzam"
];

export function isValidWilayaCode(code: number): boolean {
    return Number.isInteger(code) && code >= 1 && code <= 58;
}

export function wilayaName(code: number): string {
    return WILAYA_NAMES[code] ?? `Wilaya ${code}`;
}